# Generated by Django 4.1.5 on 2023-02-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
